### ISSUE TITLE
#60 is still an issue 

### ISSUE THREAD

**Issue by Hedwig7s** [MateriApps/OpenCord#74]
I saw #60 just died but it still happens

I reckon the app is just overloading (memory leak maybe?) with some accounts because of being in alot of servers as my alt works but not my main

**Comment by lexisother** [comment]
Why not just... bump the previous issue instead of littering the bug tracker with a new one?

**Comment by X1nto** [comment]
Hm, now that you mention that it happens when being in a lot of servers, I have some assumptions about what happens:
1. The ViewModel listeners are registered after the gateway dispatches the data, causing the data to be lost (or to be exact, not received)
2. The app already requires a lot of memory (something we're working to fix) and because of that, loading a large list of items causes a crash that for some reason isn't logged in the logcat.

Also, please, refrain from creating new issues and instead comment on currently opened issues (unless told otherwise by the maintainers)
